version: "3.8"
services:
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    volumes:
      - ./auth:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/authdb"
      JWT_SECRET: "supersecretkey"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: morzhdb

volumes:
  mongo_data:
