version: "3.8"
services:
  auth:
    build: ./auth
    ports:
      - "4000:4000"
    volumes:
      - ./auth:/app
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      MONGO_URI: "mongodb://mongodb:27017/authdb"
      JWT_SECRET: "supersecretkey"
  user:
    build: ./user
    ports:
      - "5000:5000"
    volumes:
      - ./user:/app
    environment:
      PORT: 5000
      MONGO_URI: "mongodb://mongodb:27017/userdb"
    depends_on:
      - mongodb
  general:
    build: ./general
    ports:
      - "3000:3000"
    volumes:
      - ./general:/app
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      JWT_SECRET: "supersecretkey"
      MONGO_URI: "mongodb://mongodb:27017/generaldb"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: morzhdb

volumes:
  mongo_data:
