version: "3.8"
services:
  express:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/morzhdb"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: morzhdb

volumes:
  mongo_data:
